USE [master]
GO

/****** Object:  Database [ShopContext]    Script Date: 30-07-15 4:11:55 AM ******/
CREATE DATABASE [ShopContext]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShopContext', FILENAME = N'F:\MSSQL12.MSSQLSERVER\MSSQL\DATA\ShopContext.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ShopContext_log', FILENAME = N'F:\MSSQL12.MSSQLSERVER\MSSQL\DATA\ShopContext_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ShopContext] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShopContext].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShopContext] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShopContext] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShopContext] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShopContext] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShopContext] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShopContext] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ShopContext] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShopContext] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShopContext] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShopContext] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShopContext] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShopContext] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShopContext] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShopContext] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShopContext] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ShopContext] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShopContext] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShopContext] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShopContext] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShopContext] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShopContext] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ShopContext] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShopContext] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ShopContext] SET  MULTI_USER 
GO

ALTER DATABASE [ShopContext] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShopContext] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShopContext] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShopContext] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ShopContext] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShopContext] SET  READ_WRITE 
GO


